# https://github.com/vegasbrianc/prometheus/blob/master/docker-compose.yml
# version: '3.8'

volumes:
  prometheus_data: {}

networks:
  prometheus:

services:

  prometheus:
    image: prom/prometheus:${PROMETHEUS_DOCKER_VERSION:-v2.55.0}
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
      - ./targets:/etc/prometheus/targets:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - ${PROMETHEUS_PORT:-9090}:9090
    networks:
      - prometheus
